
#include <iostream>
#include <vector>
#include <random>



//EMERGENCY ROOM SINGLE PATIENT EXPERIENCE
//by Kyle Goodale
//CS50 Final Project

//PROVIDERS

class Generators
{

public:
	Generators();
	const int sys_gen();
	const int dia_gen();
	const int pulse_gen();
	const int resp_gen();
	const float temp_gen();
	const int loc_gen();
};

class Vitals {
		
private:

	//no need for a map
	int systolic;
	int diastolic;
	int pulse;
	int resps;
	float temp;
	int loc;
	
	
public:
	Vitals(const int, const int, const int, const int, const float, const int);
	const int show_heart();
	const int show_resps();
	const int show_systolic();
	const int show_diastolic();
	const int show_loc();
	const float show_temp();
	//construct a new set of vitals with constructor function and 
    //integer arguments in proper order for 
	//systolic, diastolic, pulse, resps, temp, LOC
	//each argument should be randomly generated by the vital sign's respective function

};

class Chart
{
private:
	std::vector<Vitals*> chart;
public:
	Chart();
	void update_chart(Vitals*);
	void print_chart();
};

class Patient
{
private:
	int complaint;
public:
	Generators* p_gen;
	Chart* p_ch;
	Patient();
	int chief_complaint();
	void set_complaint(int);
	int will_see_you_now();

};

class Provider
{
protected:
	Patient* p_pt;
public:
	
	Provider(Patient*);
	void take_vital_signs();
	void chart_report();
	
};

class Nurse : public Provider
{

public:
	Nurse(Patient*);
	void triage();
	void draw_labs(const int);
	void place_iv();
	void perform_ekg();
	void pass_report();
};

class Physician : public Provider
{
private:
	Nurse* p_rn;
	
public:
	Physician(Patient*, Nurse*);
	int see_patient();
	void order_lab_tests(const int);
	void order_imaging(const int);
	void order_iv_drugs(const int);
	void emergency_procedure(const int);
	void call_consult(const int);// = new surgeon, etc.
	void admit_to_hospital();
	void pronounce_death();
};

/*//SPECIALISTS
class Surgeon : public Physician
{
public:
	Surgeon();
	void reduce_and_cast_fracture();
	void remove_foreign_body();
	void goto_operating_room();


};

class Anesthesio : public Physician
{
public:
	Anesthesio();
	void intubate_advanced();
	void give_anesthesia();
	void give_analgesia();
};

class Psychiatrist : public Physician
{
public:
	Psychiatrist();
	void order_involuntary_commit();
	void prescribe();

};
*/

int main()
{
	Patient user;
	Nurse nurse(&user);
	Physician doctor(&user, &nurse);
	const int cc = user.chief_complaint();
	user.set_complaint(cc);
	nurse.triage();
	doctor.see_patient();

}

Generators::Generators() 
{}

const int Generators::sys_gen() 
{
	std::uniform_int_distribution<unsigned> sys_range(60, 200);
	std::default_random_engine x;
	int k = sys_range(x);
	const int final = k;

	return final;

}
const int Generators::dia_gen() 
{
	std::uniform_int_distribution<unsigned> dia_range(40, 90);
	std::default_random_engine x;
	int k = dia_range(x);
	const int final = k;

	return final;

}
const int Generators::pulse_gen() 
{
	std::uniform_int_distribution<unsigned> pulse_range(40, 130);
	std::default_random_engine x;
	int k = pulse_range(x);
	const int final = k;

	return final;

}
const int Generators::resp_gen() 
{
	std::uniform_int_distribution<unsigned> resp_range(8, 30);
	std::default_random_engine x;
	int k = resp_range(x);
	const int final = k;

	return final;
}
const float Generators::temp_gen() 
{
	std::uniform_real_distribution<float> temp_range(34.0, 41.0);
	std::default_random_engine x;
	
	float k = temp_range(x);
	const float final = k;

	return final;
}
const int Generators::loc_gen() 
{
	std::uniform_int_distribution<unsigned> loc_range(3, 15);
	std::default_random_engine x;
	int k = loc_range(x);
	const int final = k;

	return final;
}



Vitals::Vitals(const int sys, const int dia, const int hr, const int rr, const float t, const int lc) //systolic, diastolic, heart rate, resp, temp, level conciousness
	:systolic(sys), diastolic(dia), pulse(hr), resps(rr), temp(t), loc(lc)
{
	
}
const int Vitals::show_heart()
{
	return Vitals::pulse;
	
}
const int Vitals::show_resps() 
{
	return Vitals::resps;
}
const int Vitals::show_systolic() 
{
	return Vitals::systolic;
}
const int Vitals::show_diastolic() 
{
	return Vitals::diastolic;
}
const int Vitals::show_loc() 
{
	return Vitals::loc;
}
const float Vitals::show_temp() 
{
	return Vitals::temp;
}
Chart::Chart() {}
void Chart::update_chart(Vitals* s) 
{
	chart.push_back(s);
}
void Chart::print_chart()
{
	for (auto i : chart)
	{
		std::cout << i->show_heart() << std::endl;
		std::cout << i->show_resps() << std::endl;
		std::cout << i->show_systolic() << std::endl;
		std::cout << i->show_diastolic() << std::endl;
		std::cout << i->show_loc() << std::endl;
		std::cout << i->show_temp() << std::endl;
	}
	
	
}

Patient::Patient()
	:complaint(0)
{
	p_ch = new Chart;
	p_gen = new Generators;
}

int Patient::chief_complaint()
{
	int input;
	std::cout << "What brings you into the emergency room?" << std::endl;
	std::cout << "Please select your complaint by typing the corresponding number and pressing enter:" << std::endl;
	std::cout << "1 - You are having chest pain." << std::endl;
	std::cout << "2 - You are having trouble breathing or are choking." << std::endl;
	std::cout << "3 - You have a headache or you think you had a seizure." << std::endl;
	std::cout << "4 - You have abdominal pain, vomiting, nausea, or diarrhea." << std::endl;
	std::cout << "5 - You fell and hit the ground or an outside force hit you, such as in a vehicular accident." << std::endl;
	std::cout << "6 - Some part of your body is not working, weak, or just 'hurting'." << std::endl;
	std::cout << "7 - You were assaulted." << std::endl;
	std::cout << "8 - You feel very sick, but none of the above." << std::endl;
	std::cout << "9 - You think you might hurt yourself on purpose." << std::endl;
	std::cout << "10 - You were exposed to extreme temperatures, drowned, or were burned." << std::endl;
	std::cin >> input;
	while (input <= 0 || input > 10)
	{
		if (std::cin.fail())
		{
			std::cin.clear();
			std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
			std::cout << "Invalid entry." << std::endl;
			std::cin >> input;
		}
	}
	return input;
}

void Patient::set_complaint(int com)
{
	complaint = com;
}

int Patient::will_see_you_now()
{
	return 1;
	
}

Provider::Provider(Patient* p)
	:p_pt(p)
{}
void Provider::take_vital_signs()
{
	
	const int systolic = p_pt->p_gen->sys_gen();
	const int diastolic = p_pt->p_gen->dia_gen();
	const int pulse = p_pt->p_gen->pulse_gen();
	const int resp = p_pt->p_gen->resp_gen();
	const float temp = p_pt->p_gen->temp_gen();
	const int loc = p_pt->p_gen->loc_gen();
	Vitals* s = new Vitals(systolic, diastolic, pulse, resp, temp, loc);
	p_pt->p_ch->update_chart(s);
}

void Provider::chart_report()
{
	p_pt->p_ch->print_chart();
}
Nurse::Nurse(Patient* q)
	:Provider(q)
{}
void Nurse::triage() 
{
	take_vital_signs();
}
void Nurse::draw_labs(const int c) {}
Physician::Physician(Patient* pt, Nurse* rn) 
	:Provider(pt), p_rn(rn)
{
}
int Physician::see_patient() 
{
	return (p_pt->will_see_you_now());
}
void Physician::order_lab_tests(const int t) {}





