#pragma once

#include <string>
#include "includes.h"
class Vitals {

private:

	int systolic;
	int diastolic;
	int pulse;
	int resps;
	double temp;
	int o2_sat;
	int loc;
	std::string time_taken;

	//Google Gemini suggested that I make these functions const
public:
	Vitals(int, int, int, int, double, int, int, std::string);
    int show_heart() const;
	int show_resps() const;
	int show_systolic() const;
	int show_diastolic() const;
	double show_temp() const;
	int show_o2_sat() const;
	int show_loc() const;
	std::string show_time() const;
	//construct a new set of vitals with constructor function and 
	//integer arguments in proper order for 
	//systolic, diastolic, pulse, resps, temp, LOC
	//each argument should be randomly generated by the vital sign's respective function

};