#pragma once
#include <string>

class Vitals {

private:

	int systolic;
	int diastolic;
	int pulse;
	int resps;
	double temp;
	int o2_sat;
	int loc;
	std::string time_taken;


public:
	Vitals(int, int, int, int, double, int, int, std::string);
    int show_heart();
	int show_resps();
	int show_systolic();
	int show_diastolic();
	double show_temp();
	int show_o2_sat();
	int show_loc();
	std::string show_time();
	//construct a new set of vitals with constructor function and 
	//integer arguments in proper order for 
	//systolic, diastolic, pulse, resps, temp, LOC
	//each argument should be randomly generated by the vital sign's respective function

};